version: '3.2'

services:
  tsplay:
    image: gillchristian/tsplay:latest
    ports:
      - "9000:${PORT}"
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./database
        target: /opt/tsplay/database
