name: 'Client: Test & Build'

on: 
  pull_request:
    branches:
      - '*'
    tags-ignore:
      - '*'
    paths:
      - 'client/**'
      - '.github/workflows/client-*'
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
    paths:
      - 'client/**'
      - '.github/workflows/client-*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn
      working-directory: client

    - name: Typecheck & Lint
      run: |
        # yarn fmt:check
        # yarn lint
        # yarn ts:check
      env:
        CI: true
      working-directory: client

    - name: Test
      run: # yarn test
      env:
        CI: true
      working-directory: client

    - name: Build
      run: yarn build
      working-directory: client
